export const REQUEST_WORDS = 'REQUEST_WORDS';
export const RETRIEVE_WORDS = 'RETRIEVE_WORDS';
export const SELECT_WORD = 'SELECT_WORD';
export const DELETE_WORD_FROM_WORDS = 'DELETE_WORD_FROM_WORDS';
export const DELETE_WORD = 'DELETE_WORD';

export const ERR_FAILED_REQUEST = 'ERR_FAILED_REQUEST';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';

export const REQUEST_IMPORT_WORDS = 'REQUEST_IMPORT_WORDS';
export const SUCCESS_IMPORT_WORDS = 'SUCCESS_IMPORT_WORDS';
export const FAIL_IMPORT_WORDS = 'FAIL_IMPORT_WORDS';

